### ISSUE TITLE
Can't specify C2 value on third CONT record of MF=1/MT=451

### ISSUE THREAD

**Issue by jlconlin** [njoy/ENDFtk#103]
A PENDF file uses the C2 value on the third CONT record of MF=1/MT=451 to specify the temperature of the ENDF Material. There currently is no way to specify that either in a constructor or with a setter.

**Comment by whaeck** [comment]
The temperature of a material actually goes into C1 and not C2 on the third line. Does NJOY2016 put it in C2 instead?

**Comment by jlconlin** [comment]
Sorry, I meant the reconstruction tolerance, not the temperature. My mistake.

**Comment by whaeck** [comment]
FIxed in #104
