### ISSUE TITLE
FindPython3

### ISSUE THREAD

**Issue by david8dixon** [njoy/ENDFtk#121]
I (unfortunately) have a machine with both python 2 and 3 installed. When building the python bindings using develop, cmake naturally finds the WRONG python. To resolve the issue, I add `find_package(Python3 REQUIRED)`. CMake does report that it finds Python3 (the corresponding path looks right). 

```
-- Found Python3: /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/bin/python3.8 
```

It also reports that it is finding PythonInterp which points to the wrong python: 

```
-- Found PythonInterp: /usr/bin/python (found version "2.7.16") 
```
so I also added `find_package(PythonInterp 3)`. After adding the latter, 

```
-- Could NOT find PythonInterp: Found unsuitable version "2.7.16", but required is at least "3" (found /usr/bin/python)
```

the above is a soft error because I did not add `REQUIRED` to `find_package(PythonInterp 3)`. Here is what I added:

```
find_package(Python3 REQUIRED)
find_package(PythonInterp 3)
```

I don't know that the second line is absolutely necessary. I would recommend at least conditionally calling `find_package(Python3 REQUIRED)` such that it is a hard requirement if you want to build the python bindings (considering python3 is required).

**Comment by whaeck** [comment]
We're actually working on releasing the current version of the python bindings soon, so we've branched off a branch with the release candidate (obviously called release). I've added the find_package for python3, it's indeed something we need to do if we want to avoid these types of issues in the future. Give it a try if you can.

I don't think the python interpreter is necessary since we don't run the python unit tests, but we may do that in the future.

**Comment by whaeck** [comment]
While playing around with Github actions, I found out that this fix only works when there is only one version of python3 installed. It still fails when multiple python3 versions are available. The best solution to the problem is to use
```
-DPYTHON_EXECUTABLE=$(which python3)
```
or replace ```$(which python3)``` with the specific python executable to use.

**Comment by david8dixon** [comment]
I was wondering if there was a config option. It worked for me on OSX...

**Comment by whaeck** [comment]
We'll have to move to the python setup tools at some point, hopefully that will allow us to fix it once and for all. We won't do that for this release though. As it stands, I'll leave it as is.

Just a quick question: where exactly did you include the find_package command?

**Comment by david8dixon** [comment]
At the top of the CMakeLists.txt. Immediately after the project call.

**Comment by whaeck** [comment]
That's where I initially put it but it leads to errors with Github actions (probably because there's multiple python3 versions on the Ubuntu 18.03 runners). I'll have to leave it out for now.

I did put some troubleshooting information in the README.md file.

**Comment by david8dixon** [comment]
Sounds good. I think the important thing is noting in the README.md:

```
-DPYTHON_EXECUTABLE=$(which python3)
```

I was not aware of this option when configuring.

**Comment by whaeck** [comment]
I've added ```-DPYTHON_EXECUTABLE=$(which python3)``` to the README.md on the release branch, right under the cmake instructions, and in the FAQ - just in case.

For the next release, we will work on some better user guide/documentation.
