### ISSUE TITLE
ENDFtk.python: gcc-11 compilation error

### ISSUE THREAD

**Issue by mwparis** [njoy/ENDFtk#133]
**Mac: CMakeFiles $ cat CMakeError.log**
Performing C++ SOURCE FILE Test HAS_FLTO failed with the following output:
Change Dir: /Users/mparis/t5500/Research/code/endf/ENDFtk/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_4173c/fast && /Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/cmTC_4173c.dir/build.make CMakeFiles/cmTC_4173c.dir/build
Building CXX object CMakeFiles/cmTC_4173c.dir/src.cxx.o
/usr/local/bin/gcc-11 -DHAS_FLTO  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk   -flto -fno-fat-lto-objects -std=gnu++17 -o CMakeFiles/cmTC_4173c.dir/src.cxx.o -c /Users/mparis/t5500/Research/code/endf/ENDFtk/build/CMakeFiles/CMakeTmp/src.cxx
cc1plus: error: '-fno-fat-lto-objects' are supported only with linker plugin
make[1]: *** [CMakeFiles/cmTC_4173c.dir/src.cxx.o] Error 1
make: *** [cmTC_4173c/fast] Error 2

Source file was:
int main() { return 0; }

**$ ipython**
Python 3.9.5 (default, May  4 2021, 03:36:27)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.24.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import ENDFtk
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-5acef2534db8> in <module>
----> 1 import ENDFtk

ImportError: dlopen(/Users/mparis/t5500/Research/code/endf/ENDFtk/build/ENDFtk.cpython-39-darwin.so, 2): Symbol not found: __ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev
  Referenced from: /Users/mparis/t5500/Research/code/endf/ENDFtk/build/ENDFtk.cpython-39-darwin.so
  Expected in: flat namespace
 in /Users/mparis/t5500/Research/code/endf/ENDFtk/build/ENDFtk.cpython-39-darwin.so

**Comment by whaeck** [comment]
I'll try to duplicate this issue on my computer. You're using gcc-11 and Python 3.9.5, I'll have to install that last one. Are you using Anaconda as a distribution, or is this the basic installation on your system?

**Comment by mwparis** [comment]
Not Anaconda; it was installed via homebrew.

Mac: ENDFtk $ python --version
Python 3.9.5

Also: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=gcc-11 ..

**Comment by whaeck** [comment]
This has been resolved: when specifying a compiler, users should use g++ instead of gcc.

On the bright side: ENDFtk works with g++-11 and Python 3.9 out of the box :-)
