### ISSUE TITLE
Add insert, insert_or_replace, remove, etc. functions to tree.Tape

### ISSUE THREAD

**Issue by whaeck** [njoy/ENDFtk#146]
This would complete the ENDFtk tree with full insertion and removal on all levels of the tree (Tape, Material and File).

**Comment by whaeck** [comment]
As a side note: the reason why this is not implemented yet is because a File and Section does not know which material it comes from. To implement these functions, we should do one of the following:
- have each File and Section know which material they are from
- add the material number as an argument of the insertion operation

**Comment by nathangibson14** [comment]
I advocate for a File and Section to know which material they come from (and for a Section to know its File).  I have never quite understood the design choices that didn't build that in.  For one thing, it'd allow mapping `print` in C++ to `__str__` in Python, which would be more natural.

I recently demonstrated how one could print a Section::3 with a different File number.  I don't see any case where that would be useful.  It's less crazy to want to do that for a MAT number, but I still don't really see a use case.  Why would someone insert a section from one Material into a different Material?

For multiple materials with the same number, my vote is to error if there are more than one material that's possible.  If that's the case, inserting really should be done at the Material level, not the Tape level.  I don't like extra arguments for temperature or material position on the tape.

**Comment by whaeck** [comment]
Completed.
