### ISSUE TITLE
TapeIdentification fails when input iterator is less than 80 characters.

### ISSUE THREAD

**Issue by jlconlin** [njoy/ENDFtk#17]
Because the ENDF line numbers (NS) are now optional, the ENDF lines do *not* have to go all the way to 80 characters.

If I create a `TapeIdentification` object and pass it an iterator that is less than 80 character (say 75), then it throws an exception with a message `Trouble reading Tail`.

Here is a valid TPID Record (from ENDF/B-VIII.0 Beta4). Take everything between the single quotes.

    ' $Rev:: 1056     $  $Date:: 2017-01-26#$                             1 0  0'

**Comment by apmccartney** [comment]
But the line needs to be terminates with a newline or an EOF character
