### ISSUE TITLE
Cannot convert to Python Type

### ISSUE THREAD

**Issue by Camden-Blake** [njoy/ENDFtk#218]
## Description  
When reading in random access arrays, a type error is thrown.  Most of the behavior is as expected and is working.  I am able to read in an ENDF file and parse out the sections I want.  However, it breaks when trying to retrieve arrays, such as energies. 

---

## Steps to Reproduce  

1. Git clone the repo and build the develop branch
2. Import ENDFtk into python
3. Read a tape from file
4. Parse desired section (such as MF7 MT2)
5. Attempt to retrieve an array (such as temperatures)

---

## Expected Behavior  
Reading in of array.

---

## Actual Behavior  
TypeError: Unregistered type : njoy::tools::views::AnyView<std::random_access_iterator_tag, double> 

---

## Environment  
- **Operating System**: Ubuntu 20.04 LTS
- **Software Version/Commit Hash**: Develop Branch
- **Compiler/Interpreter Version**: GCC 13.3
- **Other Relevant Tools/Configurations**: Python 3.12.8, CMAKE 3.28.3

---

## Log
```
TypeError: Unregistered type : njoy::tools::views::AnyView<std::random_access_iterator_tag, double>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "file.py", line xx, in <module>
    "Elastic" : read_elastic_from_endf_file(data_map[key]['endf_file_loc'])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "file.py", line xx, in read_elastic_from_endf_file
    read_coherent_elastic(scat_law)
  File "file.py", line xx, in read_coherent_elastic
    'TEMPERATURES' : tape_data.temperatures[:],
                     ^^^^^^^^^^^^^^^^^^^^^^
TypeError: Unable to convert function return value to a Python type! The signature was
	(arg0: ENDFtk.MF7.MT2.CoherentElastic) -> njoy::tools::views::AnyView<std::random_access_iterator_tag, double>

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.
```

## Python Code
```
def read_elastic_from_endf_file(file_path):
    data = {'Coherent': None, 'Incoherent': None}

    def read_coherent_elastic(tape_data):
        data['Coherent'] = {
            'TEMPERATURES' : tape_data.temperatures[:],
            'INTERPOLATION_LAWS' : tape_data.temperature_interpolants[:],
            'ENERGIES' : tape_data.energies[:],
            'S_VALUES' : np.array([item[:] for item in tape_data.thermal_scattering_values.to_list()]).flatten()
            }
        
    def read_incoherent_elastic(tape_data):
        data['Incoherent'] = {
            'TEMPERATURES' : tape_data.temperatures[:],
            'INTERPOLATION_LAW' : tape_data.interpolants[0],
            'DEBYE_WALLERS' : tape_data.debye_waller_values[:]
        }

    try:
        tape = ENDFtk.tree.Tape.from_file(str(file_path))
        mat = tape.material_numbers[0]
        mf7mt2_data = tape.material(mat).MF(7).MT(2).parse()
        scat_law = mf7mt2_data.scattering_law
        lthr = mf7mt2_data.LTHR
        if lthr == 1: # Coherent Elastic
            read_coherent_elastic(scat_law)
        elif lthr == 2: # Incoherent Elastic
            read_incoherent_elastic(scat_law)
        elif lthr == 3: # Mixed Elastic
            read_coherent_elastic(scat_law.coherent)
            read_incoherent_elastic(scat_law.incoherent)
        else:
            print(f"File {file_path.stem} has an unexpected LTHR value: {lthr}")
    except(IndexError):
        # some materials may not have any elastic scattering
        print(f"File | {file_path.stem} | Material | {mat} | does not have file 7 mt 2")

    return data
```

**Comment by whaeck** [comment]
I'm pretty sure this is because Python cannot find the tools python bindings. Inside the build folder, there should be a _deps/tools-build folder that contains a tools.*.so file. You can either use a symbolic link to this file or copy the file to where the ENDFtk python bindings are sitting. That will most likely clear up the issue.

**Comment by whaeck** [comment]
For context: we moved the AnyView bindings to its own library so that we can use ENDFtk and ACEtk together (in the past, both had bindings and that caused conflicts when loading both ENDFtk and ACEtk).

**Comment by Camden-Blake** [comment]
Yep, that cleared it right up!  I just copied to tools.*.so up into the main build directory.
