### ISSUE TITLE
Feature : additional constructor to sections, files, materials

### ISSUE THREAD

**Issue by whaeck** [njoy/ENDFtk#28]
A constructor of the following type could be interesting for users (that includes me):

```
template< typename Iterator > section( Iterator& begin, const Iterator& end ) {
  try {
    long lineNumber = 0;
    HeadRecord head( begin, end, lineNumber );
    section( head, begin, end, lineNumber, head.MAT() );
  }
  catch ( ... ) {
    // handle exceptions
  }
}
```

**Comment by apmccartney** [comment]
This would be problematic. The section syntax tree "contains" the head record in question, which, in general, can be shared by a Material, File, and Section. In other words, begin may not refer to the start of a head record.

**Comment by whaeck** [comment]
As per our discussion earlier, a factory method would be more appropriate for this feature:

```
static template< typename Iterator > section makeSection( Iterator& begin, const Iterator& end ) {
  try {
    long lineNumber = 0;
    HeadRecord head( begin, end, lineNumber );
    return section( head, begin, end, lineNumber, head.MAT() );
  }
  catch ( ... ) {
    // handle exceptions
  }
}
```

**Comment by apmccartney** [comment]
@whaeck Do the parse methods on the syntax tree suffice for this purpose?

**Comment by whaeck** [comment]
I would assume so :-)

I think we're good on this one.
