### ISSUE TITLE
Members should be private/protected with getters and setters

### ISSUE THREAD

**Issue by whaeck** [njoy/ENDFtk#29]
In some parts of the ENDFtk source code, members of classes are put in the public part of the class. These should be made private/protected and getters and setters should be added instead.

This will also help with coherence in the code.

**Comment by jlconlin** [comment]
Yeah, we have been lax about following a standard with that as our techniques have changed/improved over the last year.

**Comment by whaeck** [comment]
This is now fully addressed in #92.
