### ISSUE TITLE
missing getters

### ISSUE THREAD

**Issue by apmccartney** [njoy/ENDFtk#43]
`file::Type<N>` , `file::Type<1>`, and `file::Type<2>` does not provide a `fileNumber` getter. Delegating to the existing `MF` method should suffice.

Likewise with `section::Type` specializations have the analogous issue. Adding the method to the `section::Base` could avoid the duplication.

**Comment by whaeck** [comment]
I will add these. I am done with all of file 1 and I am currently testing it.

I will do a pull request when you're back from vacation. I hope you have good weather there, it's freezing here ;-)

**Comment by apmccartney** [comment]
https://github.com/njoy/ENDFtk/blob/master/src/ENDFtk/file/Base.hpp#L31

not const =(
