### ISSUE TITLE
ENDFtk tests fail on tail verification since disco update

### ISSUE THREAD

**Issue by whaeck** [njoy/ENDFtk#45]
The disco library was recently updated to be more flexible in its parsing of integers and doubles (e.g. left aligned instead of right aligned, etc.). Since the update, most tests in ENDFtk appear to fail due to tail verification.

For example, the ListRecord constructor throws an exception when trying to read this ENDF snippet:
````
 1.001000+3 9.991673-1          0          0         10          5 125 1451     
 0.000000+0 1.000000+0 2.000000+0 3.000000+0 4.000000+0 5.000000+0 125 1451     
 6.000000+0 7.000000+0 8.000000+0 9.000000+0                       125 1451     
````
The information given in the test report is the following:
[error] The record section number (MT) is inconsistent with expectation.
[info] The read section number is: 14
[info] The expected section number is: 451
[info] Error encountered while verifying record tail values

The code apparently tries to read the " 14" instead of "451" as the MT number in the tail verification.

It should be noted that this appears to occur only when reading sequences over multiple lines, and then only when the last line does not contain 6 entries. In the above example, the last two entries of the last line are blank.

I think the issue might be in the readPartialLine() function of the Zipper component in ENDFtk. That is how far I got in trying to figure it out.

**Comment by apmccartney** [comment]
Thank you for the example!

**Comment by whaeck** [comment]
I think this has been fixed ;-)
