### ISSUE TITLE
Need MF=2/MT152

### ISSUE THREAD

**Issue by jlconlin** [njoy/ENDFtk#72]
I need the ability to create an MF=2/MT=152 in a PENDF file.

**Comment by whaeck** [comment]
It's a relatively easy one, it's just a LIST record as far as I know. Does the NJOY manual give the format for this one, or do we have to figure it out from the source code?

We may want to implement MT153 at the same time - this contains the probability tables coming out of PURR.

**Comment by jlconlin** [comment]
The NJOY manual does describe it on page 67. It does not describe the processed MT=151 (although that can perhaps be figured out). It may describe MT=153 in PURR, but I haven't gone looking for it.
