### ISSUE TITLE
L2 parameter in CONT record in MF=3 is 99 for redundant reactions in PENDF file

### ISSUE THREAD

**Issue by jlconlin** [njoy/ENDFtk#81]
While comparing legacy PENDF files to modern PENDF files, I discovered an undocumented (surprised?) "feature". Legacy NJOY sets the `L2` parameter of the `CONT` record in MF=3 to `99` for redundant reactions. I suppose this is some sort of flag that states that this is a redundant reaction. 

What is the right way to allow this in ENDFtk? I could write another constructor for MF=3 that has a flag that it is a redundant reaction, but I suspect the `TabulationRecord` doesn't have the appropriate constructor to match.

**Comment by kahlerac** [comment]
Up through ENDF/B-V the "L2" location in select MF3/MT sections was used to hold "LFS", a variable associated with summation reactions and providing information on the final state of the residual (with "99" meaning all possible final states).  See the 1983 version of the Format Manual (Section 3.2.3) on the CSEWG Reports page.  However in the 1995 Format Manual this definition has been removed and so it appears that its continued use in legacy NJOY is an inadvertent (and hopefully harmless) error.

**Comment by whaeck** [comment]
Since this has no bearing on the ENDF6 format, and since this is never checked during construction or parsing anyway, this can be closed.
